# Generated by Django 5.2.7 on 2025-10-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма для цели'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.goal', verbose_name='Цель'),
        ),
    ]
