# Generated by Django 5.2.7 on 2025-10-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transaction_goal_amount_alter_transaction_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Накоплено'),
        ),
    ]
