# Generated by Django 5.2.7 on 2025-12-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sharedaccessinvite_sharedaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
