# Generated by Django 5.2.7 on 2025-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('planned', 'Запланировано'), ('access', 'Доступы'), ('other', 'Другое')], max_length=255, null=True),
        ),
    ]
